//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class RoomEvaluator:ProcessObject
{
	private int dIndex =0;
	private int[] directions = new int[] {2,5,7,3};
	private int product = 1;
	private int[,] grid;
	private int[] center;
	private int[] specialRooms;
	private int specialRoomCount=0;

	public RoomEvaluator (int[,] grid, int numOfRooms)
	{
		this.grid = grid;
		specialRooms = new int[numOfRooms*2];
	}

	public void AddNeighbor(int x, int y){
		if(grid[x,y] !=0){
			product *= directions[dIndex];
		}
		dIndex++;
	}

	public void AddCenter(int x, int y){
		center = new int[] {x,y};
	}

	public void Process(){
		grid[center[0],center[1]] = product;
		if(product < 10 && product != 6){
			int start = specialRoomCount*2;
			specialRooms[start] = center[0];
			specialRooms[start+1] = center[1];
			specialRoomCount++;

		}
		product =1;
		dIndex =0;
	}

	public int[] SpecialRoomList{
		get {return specialRooms;}
		set {specialRooms = value;}
	}

	public int SpecialRoomCount{
		get {return specialRoomCount;}
		set {specialRoomCount = value;}
	}


}


